server:
  port: 8081

spring:
  application:
    name: link-shortener
  datasource:
    url: jdbc:postgresql://localhost:5433/mentoring
    username: dev
    password: dev
    hikari:
      schema: link_shortener
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

link-shortener:
  short-link-length: 8
  enable-log-exec-time: true